import "./globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import Background from "@/components/background";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={` min-h-screen flex`}>
        <Background>
        {children}
        </Background>
        </body>
    </html>
  );
}
