export const HTTP_BACKEND_URL = process.env.NEXT_PUBLIC_HTTP_BACKEND_URL
export const GOOGLE_CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ?? ""
export const GOOGLE_REDIRECT_URI_SIGNUP = process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URL_SIGNUP ?? ""
export const GOOGLE_REDIRECT_URI_LOGIN = process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URL_LOGIN ?? ""

export const GOOGLE_AUTH_URI = process.env.NEXT_PUBLIC_GOOGLE_AUTH_URL

